project:
  type: website
  title: "rinchenlama"
  output-dir: docs
  


website:
  favicon: assets/favicon.png
  title: "Welcome!"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: pages/work.qmd
        text: Work
      - href: pages/projects.qmd
        text: Projects
      - href: pages/resume.qmd
        text: Resume
  sidebar:
    # - title: Contact Me
    logo: assets/Rinchen Lama.jpeg
    alt: "Rinchen's best looking photo"
    tools: 
      - icon: envelope-at-fill
        href: rruit0075@gmail.com
      - icon: linkedin
        href: https://www.linkedin.com/rinchenlama0075
      - icon: instagram
        href: https://www.instagram.com/rinchen_ruit/
      - icon: github
        href: https://github.com/rinchenlama0075
    
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: style.css
    toc: true


